### PR TITLE
Slider Gesture Control PR Update.

### PR DESCRIPTION
**Pull request by StephenHodgson**
Updated SliderGestureControl with a non unity event.
Removed UnityEventFloat.

In order to get your updated slider information, you'd want to get the SliderGestureControl component (Or make a field to set the value in the inspector if it's known ahead of time) and then subscribe to the OnSliderEvent in your StudentHeatMapManager:

```
[SerializeField]
private SliderGestureControl sliderGestureControl;

private void Awake()
{
    sliderGestureControl.OnSliderUpdate += OnSliderUpdated;
}

private void OnSliderUpdated(float value)
{
    // Do stuff with your value.
}
```

### CODE REVIEW

**Comment by StephenHodgson** [comment]
I also did some cleaning up in the class to make them conform to the MRTK's coding guidelines.

**Comment by Gaweph** [comment]
I have created a new PR that targets the Stabilization branch in order to address the minor change of passing the value through with the current event implementation.

**Comment by Gaweph** [comment]
Regarding this refactor (events to c# Actions) should we also consider targeting all other controls, its a fundamental change to how the controls will be interacted with, currently all controls use UnityEvents?

Also, my initial thought is that this change is making the controls less accessible to novice users, as it looses the unity editor support for managing the onUpdate action of the slider control.

What are you thoughts on this?

**Comment by StephenHodgson** [comment]
Devs should know how to use actions in Unity.  tbh, the UnityEvent is harder to consume and use.

**Comment by Gaweph** [comment]
Thanks Stephen, I will use in my project and start looking at other controls 👍

**Comment by Gaweph** [comment]
@StephenHodgson What is the preferred method of keeping my fork up to date with the upstream Microsoft repository?  I have been merging the MS repo back into mine, but this is causing me to be commits ahead of Microsoft.

Any advice welcome.

**Pull request merged**
